<?php


namespace Database\Seeds;


use App\Models\Champion;
use Artemis\Core\Database\Seeder;


class ChampionSeeder extends Seeder
{
    /**
     * @inheritDoc
     */
    public function run() : void
    {
        $this->freshSeedReset('db', 'champions');

        Champion::query()->insert([
            ['name' => 'Aatrox', 'icon_path' => 'img/champions/icons/AatroxSquare.png'],
            ['name' => 'Ahri', 'icon_path' => 'img/champions/icons/AhriSquare.png'],
            ['name' => 'Akali', 'icon_path' => 'img/champions/icons/AkaliSquare.png'],
            ['name' => 'Akshan', 'icon_path' => 'img/champions/icons/AkshanSquare.png'],
            ['name' => 'Alistar', 'icon_path' => 'img/champions/icons/AlistarSquare.png'],
            ['name' => 'Amumu', 'icon_path' => 'img/champions/icons/AmumuSquare.png'],
            ['name' => 'Anivia', 'icon_path' => 'img/champions/icons/AniviaSquare.png'],
            ['name' => 'Annie', 'icon_path' => 'img/champions/icons/AnnieSquare.png'],
            ['name' => 'Aphelios', 'icon_path' => 'img/champions/icons/ApheliosSquare.png'],
            ['name' => 'Ashe', 'icon_path' => 'img/champions/icons/AsheSquare.png'],
            ['name' => 'Aurelion Sol', 'icon_path' => 'img/champions/icons/Aurelion_SolSquare.png'],
            ['name' => 'Azir', 'icon_path' => 'img/champions/icons/AzirSquare.png'],
            ['name' => 'Bard', 'icon_path' => 'img/champions/icons/BardSquare.png'],
            ['name' => 'Blitzcrank', 'icon_path' => 'img/champions/icons/BlitzcrankSquare.png'],
            ['name' => 'Brand', 'icon_path' => 'img/champions/icons/BrandSquare.png'],
            ['name' => 'Braum', 'icon_path' => 'img/champions/icons/BraumSquare.png'],
            ['name' => 'Caitlyn', 'icon_path' => 'img/champions/icons/CaitlynSquare.png'],
            ['name' => 'Camille', 'icon_path' => 'img/champions/icons/CamilleSquare.png'],
            ['name' => 'Cassiopeia', 'icon_path' => 'img/champions/icons/CassiopeiaSquare.png'],
            ['name' => 'Cho\'Gath', 'icon_path' => 'img/champions/icons/Cho\'GathSquare.png'],
            ['name' => 'Corki', 'icon_path' => 'img/champions/icons/CorkiSquare.png'],
            ['name' => 'Darius', 'icon_path' => 'img/champions/icons/DariusSquare.png'],
            ['name' => 'Diana', 'icon_path' => 'img/champions/icons/DianaSquare.png'],
            ['name' => 'Dr. Mundo', 'icon_path' => 'img/champions/icons/Dr._MundoSquare.png'],
            ['name' => 'Draven', 'icon_path' => 'img/champions/icons/DravenSquare.png'],
            ['name' => 'Ekko', 'icon_path' => 'img/champions/icons/EkkoSquare.png'],
            ['name' => 'Elise', 'icon_path' => 'img/champions/icons/EliseSquare.png'],
            ['name' => 'Evelynn', 'icon_path' => 'img/champions/icons/EvelynnSquare.png'],
            ['name' => 'Ezreal', 'icon_path' => 'img/champions/icons/EzrealSquare.png'],
            ['name' => 'Fiddlesticks', 'icon_path' => 'img/champions/icons/FiddlesticksSquare.png'],
            ['name' => 'Fiora', 'icon_path' => 'img/champions/icons/FioraSquare.png'],
            ['name' => 'Fizz', 'icon_path' => 'img/champions/icons/FizzSquare.png'],
            ['name' => 'Galio', 'icon_path' => 'img/champions/icons/GalioSquare.png'],
            ['name' => 'Gangplank', 'icon_path' => 'img/champions/icons/GangplankSquare.png'],
            ['name' => 'Garen', 'icon_path' => 'img/champions/icons/GarenSquare.png'],
            ['name' => 'Gnar', 'icon_path' => 'img/champions/icons/GnarSquare.png'],
            ['name' => 'Gragas', 'icon_path' => 'img/champions/icons/GragasSquare.png'],
            ['name' => 'Graves', 'icon_path' => 'img/champions/icons/GravesSquare.png'],
            ['name' => 'Gwen', 'icon_path' => 'img/champions/icons/GwenSquare.png'],
            ['name' => 'Hecarim', 'icon_path' => 'img/champions/icons/HecarimSquare.png'],
            ['name' => 'Heimerdinger', 'icon_path' => 'img/champions/icons/HeimerdingerSquare.png'],
            ['name' => 'Illaoi', 'icon_path' => 'img/champions/icons/IllaoiSquare.png'],
            ['name' => 'Irelia', 'icon_path' => 'img/champions/icons/IreliaSquare.png'],
            ['name' => 'Ivern', 'icon_path' => 'img/champions/icons/IvernSquare.png'],
            ['name' => 'Janna', 'icon_path' => 'img/champions/icons/JannaSquare.png'],
            ['name' => 'Jarvan IV', 'icon_path' => 'img/champions/icons/Jarvan_IVSquare.png'],
            ['name' => 'Jax', 'icon_path' => 'img/champions/icons/JaxSquare.png'],
            ['name' => 'Jayce', 'icon_path' => 'img/champions/icons/JayceSquare.png'],
            ['name' => 'Jhin', 'icon_path' => 'img/champions/icons/JhinSquare.png'],
            ['name' => 'Jinx', 'icon_path' => 'img/champions/icons/JinxSquare.png'],
            ['name' => 'Kai\'Sa', 'icon_path' => 'img/champions/icons/Kai\'SaSquare.png'],
            ['name' => 'Kalista', 'icon_path' => 'img/champions/icons/KalistaSquare.png'],
            ['name' => 'Karma', 'icon_path' => 'img/champions/icons/KarmaSquare.png'],
            ['name' => 'Karthus', 'icon_path' => 'img/champions/icons/KarthusSquare.png'],
            ['name' => 'Kassadin', 'icon_path' => 'img/champions/icons/KassadinSquare.png'],
            ['name' => 'Katarina', 'icon_path' => 'img/champions/icons/KatarinaSquare.png'],
            ['name' => 'Kayle', 'icon_path' => 'img/champions/icons/KayleSquare.png'],
            ['name' => 'Kayn', 'icon_path' => 'img/champions/icons/KaynSquare.png'],
            ['name' => 'Kennen', 'icon_path' => 'img/champions/icons/KennenSquare.png'],
            ['name' => 'Kha\'Zix', 'icon_path' => 'img/champions/icons/Kha\'ZixSquare.png'],
            ['name' => 'Kindred', 'icon_path' => 'img/champions/icons/KindredSquare.png'],
            ['name' => 'Kled', 'icon_path' => 'img/champions/icons/KledSquare.png'],
            ['name' => 'Kog\'Maw', 'icon_path' => 'img/champions/icons/Kog\'MawSquare.png'],
            ['name' => 'LeBlanc', 'icon_path' => 'img/champions/icons/LeBlancSquare.png'],
            ['name' => 'Lee Sin', 'icon_path' => 'img/champions/icons/Lee_SinSquare.png'],
            ['name' => 'Leona', 'icon_path' => 'img/champions/icons/LeonaSquare.png'],
            ['name' => 'Lillia', 'icon_path' => 'img/champions/icons/LilliaSquare.png'],
            ['name' => 'Lissandra', 'icon_path' => 'img/champions/icons/LissandraSquare.png'],
            ['name' => 'Lucian', 'icon_path' => 'img/champions/icons/LucianSquare.png'],
            ['name' => 'Lulu', 'icon_path' => 'img/champions/icons/LuluSquare.png'],
            ['name' => 'Lux', 'icon_path' => 'img/champions/icons/LuxSquare.png'],
            ['name' => 'Malphite', 'icon_path' => 'img/champions/icons/MalphiteSquare.png'],
            ['name' => 'Malzahar', 'icon_path' => 'img/champions/icons/MalzaharSquare.png'],
            ['name' => 'Maokai', 'icon_path' => 'img/champions/icons/MaokaiSquare.png'],
            ['name' => 'Master Yi', 'icon_path' => 'img/champions/icons/Master_YiSquare.png'],
            ['name' => 'Miss Fortune', 'icon_path' => 'img/champions/icons/MissFortuneSquare.png'],
            ['name' => 'Mordekaiser', 'icon_path' => 'img/champions/icons/MordekaiserSquare.png'],
            ['name' => 'Morgana', 'icon_path' => 'img/champions/icons/MorganaSquare.png'],
            ['name' => 'Nami', 'icon_path' => 'img/champions/icons/NamiSquare.png'],
            ['name' => 'Nasus', 'icon_path' => 'img/champions/icons/NasusSquare.png'],
            ['name' => 'Nautilus', 'icon_path' => 'img/champions/icons/NautilusSquare.png'],
            ['name' => 'Neeko', 'icon_path' => 'img/champions/icons/NeekoSquare.png'],
            ['name' => 'Nidalee', 'icon_path' => 'img/champions/icons/NidaleeSquare.png'],
            ['name' => 'Nocturne', 'icon_path' => 'img/champions/icons/NocturneSquare.png'],
            ['name' => 'Nunu & Willump', 'icon_path' => 'img/champions/icons/Nunu_&_WillumpSquare.png'],
            ['name' => 'Olaf', 'icon_path' => 'img/champions/icons/OlafSquare.png'],
            ['name' => 'Orianna', 'icon_path' => 'img/champions/icons/OriannaSquare.png'],
            ['name' => 'Ornn', 'icon_path' => 'img/champions/icons/OrnnSquare.png'],
            ['name' => 'Pantheon', 'icon_path' => 'img/champions/icons/PantheonSquare.png'],
            ['name' => 'Poppy', 'icon_path' => 'img/champions/icons/PoppySquare.png'],
            ['name' => 'Pyke', 'icon_path' => 'img/champions/icons/PykeSquare.png'],
            ['name' => 'Qiyana', 'icon_path' => 'img/champions/icons/QiyanaSquare.png'],
            ['name' => 'Quinn', 'icon_path' => 'img/champions/icons/QuinnSquare.png'],
            ['name' => 'Rakan', 'icon_path' => 'img/champions/icons/RakanSquare.png'],
            ['name' => 'Rammus', 'icon_path' => 'img/champions/icons/RammusSquare.png'],
            ['name' => 'Rek\'Sai', 'icon_path' => 'img/champions/icons/Rek\'SaiSquare.png'],
            ['name' => 'Rell', 'icon_path' => 'img/champions/icons/RellSquare.png'],
            ['name' => 'Renekton', 'icon_path' => 'img/champions/icons/RenektonSquare.png'],
            ['name' => 'Rengar', 'icon_path' => 'img/champions/icons/RengarSquare.png'],
            ['name' => 'Riven', 'icon_path' => 'img/champions/icons/RivenSquare.png'],
            ['name' => 'Rumble', 'icon_path' => 'img/champions/icons/RumbleSquare.png'],
            ['name' => 'Ryze', 'icon_path' => 'img/champions/icons/RyzeSquare.png'],
            ['name' => 'Samira', 'icon_path' => 'img/champions/icons/SamiraSquare.png'],
            ['name' => 'Sejuani', 'icon_path' => 'img/champions/icons/SejuaniSquare.png'],
            ['name' => 'Senna', 'icon_path' => 'img/champions/icons/SennaSquare.png'],
            ['name' => 'Seraphine', 'icon_path' => 'img/champions/icons/SeraphineSquare.png'],
            ['name' => 'Sett', 'icon_path' => 'img/champions/icons/SettSquare.png'],
            ['name' => 'Shaco', 'icon_path' => 'img/champions/icons/ShacoSquare.png'],
            ['name' => 'Shen', 'icon_path' => 'img/champions/icons/ShenSquare.png'],
            ['name' => 'Shyvana', 'icon_path' => 'img/champions/icons/ShyvanaSquare.png'],
            ['name' => 'Singed', 'icon_path' => 'img/champions/icons/SingedSquare.png'],
            ['name' => 'Sion', 'icon_path' => 'img/champions/icons/SionSquare.png'],
            ['name' => 'Sivir', 'icon_path' => 'img/champions/icons/SivirSquare.png'],
            ['name' => 'Skarner', 'icon_path' => 'img/champions/icons/SkarnerSquare.png'],
            ['name' => 'Sona', 'icon_path' => 'img/champions/icons/SonaSquare.png'],
            ['name' => 'Soraka', 'icon_path' => 'img/champions/icons/SorakaSquare.png'],
            ['name' => 'Swain', 'icon_path' => 'img/champions/icons/SwainSquare.png'],
            ['name' => 'Sylas', 'icon_path' => 'img/champions/icons/SylasSquare.png'],
            ['name' => 'Syndra', 'icon_path' => 'img/champions/icons/SyndraSquare.png'],
            ['name' => 'Tahm Kench', 'icon_path' => 'img/champions/icons/Tahm_KenchSquare.png'],
            ['name' => 'Taliyah', 'icon_path' => 'img/champions/icons/TaliyahSquare.png'],
            ['name' => 'Talon', 'icon_path' => 'img/champions/icons/TalonSquare.png'],
            ['name' => 'Taric', 'icon_path' => 'img/champions/icons/TaricSquare.png'],
            ['name' => 'Teemo', 'icon_path' => 'img/champions/icons/TeemoSquare.png'],
            ['name' => 'Thresh', 'icon_path' => 'img/champions/icons/ThreshSquare.png'],
            ['name' => 'Tristana', 'icon_path' => 'img/champions/icons/TristanaSquare.png'],
            ['name' => 'Trundle', 'icon_path' => 'img/champions/icons/TrundleSquare.png'],
            ['name' => 'Tryndamere', 'icon_path' => 'img/champions/icons/TryndamereSquare.png'],
            ['name' => 'Twisted Fate', 'icon_path' => 'img/champions/icons/Twisted_FateSquare.png'],
            ['name' => 'Twitch', 'icon_path' => 'img/champions/icons/TwitchSquare.png'],
            ['name' => 'Udyr', 'icon_path' => 'img/champions/icons/UdyrSquare.png'],
            ['name' => 'Urgot', 'icon_path' => 'img/champions/icons/UrgotSquare.png'],
            ['name' => 'Varus', 'icon_path' => 'img/champions/icons/VarusSquare.png'],
            ['name' => 'Vayne', 'icon_path' => 'img/champions/icons/VayneSquare.png'],
            ['name' => 'Veigar', 'icon_path' => 'img/champions/icons/VeigarSquare.png'],
            ['name' => 'Vel\'Koz', 'icon_path' => 'img/champions/icons/Vel\'KozSquare.png'],
            ['name' => 'Vex', 'icon_path' => 'img/champions/icons/VexSquare.png'],
            ['name' => 'Viego', 'icon_path' => 'img/champions/icons/ViegoSquare.png'],
            ['name' => 'Viktor', 'icon_path' => 'img/champions/icons/ViktorSquare.png'],
            ['name' => 'Vi', 'icon_path' => 'img/champions/icons/ViSquare.png'],
            ['name' => 'Vladimir', 'icon_path' => 'img/champions/icons/VladimirSquare.png'],
            ['name' => 'Volibear', 'icon_path' => 'img/champions/icons/VolibearSquare.png'],
            ['name' => 'Warwick', 'icon_path' => 'img/champions/icons/WarwickSquare.png'],
            ['name' => 'Wukong', 'icon_path' => 'img/champions/icons/WukongSquare.png'],
            ['name' => 'Xayah', 'icon_path' => 'img/champions/icons/XayahSquare.png'],
            ['name' => 'Xerath', 'icon_path' => 'img/champions/icons/XerathSquare.png'],
            ['name' => 'Xin Zhao', 'icon_path' => 'img/champions/icons/Xin_ZhaoSquare.png'],
            ['name' => 'Yasuo', 'icon_path' => 'img/champions/icons/YasuoSquare.png'],
            ['name' => 'Yone', 'icon_path' => 'img/champions/icons/YoneSquare.png'],
            ['name' => 'Yorick', 'icon_path' => 'img/champions/icons/YorickSquare.png'],
            ['name' => 'Yuumi', 'icon_path' => 'img/champions/icons/YuumiSquare.png'],
            ['name' => 'Zac', 'icon_path' => 'img/champions/icons/ZacSquare.png'],
            ['name' => 'Zed', 'icon_path' => 'img/champions/icons/ZedSquare.png'],
            ['name' => 'Ziggs', 'icon_path' => 'img/champions/icons/ZiggsSquare.png'],
            ['name' => 'Zilean', 'icon_path' => 'img/champions/icons/ZileanSquare.png'],
            ['name' => 'Zoe', 'icon_path' => 'img/champions/icons/ZoeSquare.png'],
            ['name' => 'Zyra', 'icon_path' => 'img/champions/icons/ZyraSquare.png'],
            ['name' => 'Zeri', 'icon_path' => 'img/champions/icons/ZeriSquare.png'],
        ]);
    }
}